spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: 'root'
      password: 'root@01234560'
      url: 'jdbc:mysql://127.0.0.1:3306/distribute_id?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8'
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: root
        url-pattern: /druid/*
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  redis:
    redisson:
      file: classpath:redisson.yml
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
log:
  path: './logs'


