spring.application.name=spring-batch-demo
spring.datasource.url=jdbc:h2:file:./data/spring-batch-demo;MODE=MYSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never
spring.profiles.active=dev