spring:
  redis:
    database: 0
    sentinel:
      master: 'mymaster'
      nodes:
        - "redis://127.0.0.1:26383"
        - "redis://127.0.0.1:26382"
        - "redis://127.0.0.1:26381"
#      password
    lettuce:
      pool:
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
    redisson:
      file: classpath:redisson.yml