server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: 'root'
      password: 'root@01234560'
      url: 'jdbc:mysql://127.0.0.1:33060/message_push?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8'
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
        url-pattern: /druid/*
  redis:
    # https://github.com/redisson/redisson/wiki/2.-Configuration
    database: '0'
    host: '127.0.0.1'
    port: '6379'
    password: 'redis@01234560'
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: ${mail.password}
    port: 465
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          socketFactory:
            class:  'javax.net.ssl.SSLSocketFactory'
    protocol: smtp
    test-connection: true
    username: ${mail.username}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  #mapper.xml
  configuration:
    map-underscore-to-camel-case: true #
