DROP TABLE IF EXISTS sys_message_template;
CREATE TABLE sys_message_template(
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    ID BIGINT(19) NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    TEMPLATE_TITLE VARCHAR(64) NOT NULL   COMMENT '模板标题' ,
    TEMPLATE_NAME VARCHAR(64)    COMMENT '消息名称' ,
    TEMPLATE_CODE VARCHAR(64) NOT NULL   COMMENT '消息模板编码' ,
    TEMPLATE_CONTENT VARCHAR(900)    COMMENT '消息内容 占位符用${var}表示' ,
    EXTERNAL_CODE VARCHAR(64)    COMMENT '外部编码' ,
    ENABLED_FLAG char(1)    COMMENT '启用标识' ,
    CHANNEL VARCHAR(64)    COMMENT '发送渠道' ,
    JUMP_URL VARCHAR(255)    COMMENT '跳转url' ,
    PRIMARY KEY (ID)
)  COMMENT = '消息模板表';

DROP TABLE IF EXISTS sys_message;
CREATE TABLE sys_message(
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    ID BIGINT(19) NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    SUBJECT VARCHAR(255) NOT NULL   COMMENT '消息标题' ,
    CONTENT VARCHAR(255) NOT NULL   COMMENT '消息内容' ,
    TEMPLATE_CODE VARCHAR(255)    COMMENT '模板编码' ,
    PUBLISH_USER_ID BIGINT(19) NOT NULL   COMMENT '发布人ID' ,
    SEND_FLAG char(1)    COMMENT '发送标识：0未发送、1已发送' ,
    PRIMARY KEY (ID)
)  COMMENT = '消息主表';

DROP TABLE IF EXISTS sys_user_message;
CREATE TABLE sys_user_message(
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    ID BIGINT(19) NOT NULL AUTO_INCREMENT  COMMENT '' ,
    MESSAGE_ID BIGINT(19) NOT NULL   COMMENT '消息主表ID' ,
    IS_READ char(1)   DEFAULT '0' COMMENT '是否已读：0否、1是' ,
    RECIPIENT_ID BIGINT(19) NOT NULL   COMMENT '接受通知的用户的ID' ,
    PRIMARY KEY (ID)
)  COMMENT = '用户消息表';

DROP TABLE IF EXISTS sys_message_type;
CREATE TABLE sys_message_type(
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    ID BIGINT(19) NOT NULL AUTO_INCREMENT  COMMENT '' ,
    MESSAGE_CODE VARCHAR(64) NOT NULL   COMMENT '消息代码' ,
    MESSAGE_NAME VARCHAR(64) NOT NULL   COMMENT '消息名称' ,
    ENABLED_FLAG char(1) NOT NULL   COMMENT '启用标识' ,
    DESCRIPTION VARCHAR(255)    COMMENT '描述' ,
    PRIMARY KEY (ID)
)  COMMENT = '消息模板类型';

DROP TABLE IF EXISTS sys_message_type_ref;
CREATE TABLE sys_message_type_ref(
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    ID BIGINT(19) NOT NULL AUTO_INCREMENT  COMMENT '' ,
    TEMPLATE_CODE VARCHAR(64) NOT NULL   COMMENT '消息模板编码' ,
    TEMP_SERVER_ID BIGINT(19)    COMMENT '模板类型ID;sys_template_server.id' ,
    TYPE_CODE VARCHAR(64)    COMMENT '模版类型;WEB、SMS、EMAIL' ,
    ENABLED_FLAG CHAR(1)    COMMENT '启用标识' ,
    PRIMARY KEY (ID)
)  COMMENT = '消息模板类型关联';

DROP TABLE IF EXISTS sys_user_message_config;
CREATE TABLE sys_user_message_config(
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    ID BIGINT(19) NOT NULL AUTO_INCREMENT  COMMENT '' ,
    USER_ID BIGINT(19) NOT NULL   COMMENT '用户ID' ,
    MESSAGE_CODE VARCHAR(64) NOT NULL   COMMENT '消息编码' ,
    WEB char(1) NOT NULL  DEFAULT '1' COMMENT '是否发送站内信' ,
    SMS char(1) NOT NULL  DEFAULT '1' COMMENT '是否发送短信' ,
    EMAIL char(1) NOT NULL  DEFAULT '1' COMMENT '是否发送邮件' ,
    OFFICIAL_WECHAT char(1) NOT NULL  DEFAULT '1' COMMENT '是否发送微信公众号' ,
    PRIMARY KEY (ID)
)  COMMENT = '用户消息配置';

