DROP TABLE IF EXISTS `STUDENT`;

CREATE TABLE STUDENT (
	ID INT auto_increment NOT NULL,
	SNO varchar(8) NOT NULL COMMENT '学号',
	SNAME varchar(4) NULL COMMENT '学生名称',
	SSEX varchar(2) NULL COMMENT '性别',
	SBIRTHDAY DATETIME NULL COMMENT '生日',
	CLASS varchar(5) NULL COMMENT '班级',
	CONSTRAINT STUDENT_pk PRIMARY KEY (ID),
	CONSTRAINT STUDENT_un UNIQUE KEY (SNO)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='学生表';


DROP TABLE IF EXISTS `COURSE`;

CREATE TABLE COURSE (
	ID INT auto_increment NOT NULL,
	CNO VARCHAR(5) NOT NULL COMMENT '课程号',
	CNAME varchar(104) NULL COMMENT '课程名称',
	TNO VARCHAR(10) NULL COMMENT '老师编号',
	CONSTRAINT COURSE_pk PRIMARY KEY (ID),
	CONSTRAINT COURSE_un UNIQUE KEY (CNO)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='课程表';


DROP TABLE IF EXISTS `SCORE`;

CREATE TABLE SCORE (
	ID INT auto_increment NOT NULL,
	SNO VARCHAR(8) NOT NULL COMMENT '学生号',
	CNO VARCHAR(8) NULL COMMENT '课程号',
	`DEGREE` decimal(4,1) NULL COMMENT '成绩',
	CONSTRAINT SCORE_pk PRIMARY KEY (ID),
	CONSTRAINT SCORE_un UNIQUE KEY (SNO,CNO)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='成绩表';

DROP TABLE IF EXISTS `TEACHER`;

CREATE TABLE TEACHER (
	ID INT auto_increment NOT NULL,
	TNO VARCHAR(8) NOT NULL COMMENT '老师编码',
	TNAME VARCHAR(4) NOT NULL COMMENT '老师名称',
	TSEX VARCHAR(2) NOT NULL COMMENT '老师性别',
	TBIRTHDAY DATETIME NULL COMMENT '老师生日',
	PROF VARCHAR(6) COMMENT '职称',
	DEPART VARCHAR(10) NOT NULL COMMENT '部门',
	CONSTRAINT TEACHER_pk PRIMARY KEY (ID),
	CONSTRAINT TEACHER_un UNIQUE KEY (TNO)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='老师表';


DROP TABLE IF EXISTS `GRADE`;

CREATE TABLE GRADE (
	ID INT auto_increment NOT NULL,
	`low` decimal(4,1) DEFAULT null COMMENT '下限',
	  `upp` decimal(4,1) DEFAULT null COMMENT '上限',
	  `rank` char(1) DEFAULT null COMMENT '排名',
	CONSTRAINT GRADE_pk PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='排名';